### ISSUE TITLE
Link crates.io listing in readme

### ISSUE THREAD

**Issue by NotThatRqd** [jedisct1/rust-cpace#8]
The crates.io listing (https://crates.io/crates/pake-cpace/) should be added to the readme or somewhere else so people on the repository on github can find it on crates.io

**Comment by jedisct1** [comment]
Hi,

There's a badge, that links to the documentation on `docs.rs`.

What added value would the `crates.io` website bring to this?

That being said, a PR would be welcome.

**Comment by NotThatRqd** [comment]
Oh sorry, I didn't see the badge haha, instead I found the name of it to use in my cargo.toml with google
